Universidade/Macoratti University - EF Core/Models/CursoViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Universidade.Models
{
    public class CursoViewModel
    {
        public int CursoID { get; set; }
        
        [Required]
        [StringLength(100, ErrorMessage = "O título não pode ter mais que 100 caracteres.")]
        [RegularExpression(@"^(?:[a-zA-Z]+\s?)+[a-zA-Z]+$", ErrorMessage = "O título deve conter apenas letras")]
        public string Titulo { get; set; }
        
        [Required]
        [Range(0, 99, ErrorMessage = "Os créditos não podem ter mais que 2 caracteres.")]
        public int Creditos { get; set; }
        public ICollection<MatriculaViewModel> Matriculas { get; set; }
        
        [Required]
        public int DepartamentoID { get; set; }

        [Display(Name ="Alocação Máxima")]
        public int LotacaoAlunos { get; set; }
        public DepartamentoViewModel Departamento { get; set; }

        [Display(Name="Nº de Alunos")]
        public int QuantidadeMatriculas { 
            get 
            {
                return Matriculas != null ? Matriculas.Count : 0; 
            } 
        }
    }
}

Universidade/Macoratti University - EF Core/Controllers/CursosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Universidade.Models;
using AutoMapper;
using Universidade.Infrastructure;
using Universidade.Core.Entidades;
using Universidade.Utility;

namespace Universidade.Controllers
{
    public class CursosController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public CursosController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var lCursos = await _unitOfWork.Cursos.ListarCursosDepartamentoEMatriculas();

            return View(lCursos.Select(x => _mapper.Map<CursoViewModel>(x)));
        }

        public async Task<IActionResult> Detalhes(int? id)
        {
            if (id == null)
                return NotFound();

            var lCurso = await _unitOfWork.Cursos.BuscarCursoDepartamentoEMatriculasPorCursoId(id.Value);

            if (lCurso == null)
                return NotFound();

            var lCursoViewModel = _mapper.Map<CursoViewModel>(lCurso);

            return View(lCursoViewModel);
        }

        public IActionResult Inserir()
        {
            ViewBag.SelectListDepartamentos = MontarSelectListDepartamentos();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Inserir([Bind("CursoID,Titulo,Creditos,DepartamentoID,LotacaoAlunos")] CursoViewModel curso)
        {
            if (curso == null)
                return NotFound();

            try
            {
                if (ModelState.IsValid)
                {
                    var lCurso = _mapper.Map<Curso>(curso);
                    lCurso.Validar();

                    if (lCurso.MensagensErro.Any())
                    {
                        this.AdicionarMensagemDeErro(String.Format(", ", lCurso.MensagensErro));
                        return View(lCurso);
                    }

                    _unitOfWork.Cursos.Adicionar(lCurso);
                    _unitOfWork.Complete();

                    this.AdicionarMensagemDeSucesso("Curso inserido com sucesso!");
                    return RedirectToAction(nameof(Index));
                }

                return RedirectToAction(nameof(Inserir));
            }
            catch (Exception)
            {
                this.AdicionarMensagemDeErro("Não foi possível salvar. Tente novamente, e se o problema persistir chame o suporte.");
                return RedirectToAction(nameof(Inserir));
            }
        }
        
        public async Task<IActionResult> Editar(int? id)
        {
            Curso lCurso = null;

            if (id == null)
                return NotFound();

            try
            {
                lCurso = await _unitOfWork.Cursos.BuscarCursoDepartamentoEMatriculasPorCursoId(id.Value);
                ViewBag.SelectListDepartamentos = MontarSelectListDepartamentos(lCurso);

                if (lCurso == null)
                    return NotFound();
            }
            catch(Exception e)
            {
                this.AdicionarMensagemDeErro("Não foi possível salvar. Tente novamente, e se o problema persistir chame o suporte.");
            }

            return View(_mapper.Map<CursoViewModel>(lCurso));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ConfirmarEdicao([Bind("CursoID,Titulo,Creditos,DepartamentoID,LotacaoAlunos")] CursoViewModel curso, string idsEstudantesMatriculados)
        {
            if (curso == null)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    var lCurso = _mapper.Map<Curso>(curso);
                    lCurso.Validar();

                    if (lCurso.MensagensErro.Any())
                    {
                        this.AdicionarMensagemDeErro(String.Join(", ", lCurso.MensagensErro));
                        return View(nameof(Editar), curso);
                    }

                    _unitOfWork.Cursos.Editar(lCurso);
                    _unitOfWork.Complete();

                    return RedirectToAction(nameof(Index));
                }
                catch (Exception e)
                {
                    this.AdicionarMensagemDeErro("Não foi possível salvar. Tente novamente, e se o problema persistir chame o suporte.");
                    return RedirectToAction(nameof(Editar), new { id = curso.CursoID });
                }
            }

            return View(nameof(Editar), curso);
        }

        public async Task<IActionResult> Excluir(int? id, bool? saveChangesError = false)
        {
            if (id == null)
                return NotFound();
            CursoViewModel lCursoViewModel;

            try
            {
                var lCurso = await _unitOfWork.Cursos.BuscarCursoDepartamentoEMatriculasPorCursoId(id.Value);

                if (lCurso == null)
                    return NotFound();

                if (saveChangesError.GetValueOrDefault())
                    this.AdicionarMensagemDeErro("A exclusão falhou. Tente novamente e se o problema persistir contate o suporte.");

                lCursoViewModel = _mapper.Map<CursoViewModel>(lCurso);
            }
            catch(Exception e)
            {
                this.AdicionarMensagemDeErro("Não foi possível executar a operação. Tente novamente, e se o problema persistir chame o suporte.");
                return RedirectToAction(nameof(Index));
            }

            return View(lCursoViewModel);
        }

        [HttpPost, ActionName("Excluir")]
        [ValidateAntiForgeryToken]
        public IActionResult ConfirmarExclusao(int id)
        {
            try
            {
                _unitOfWork.Cursos.Deletar(id);
                _unitOfWork.Complete();
            }
            catch(Exception e)
            {
                this.AdicionarMensagemDeErro("Não foi possível executar a operação. Tente novamente, e se o problema persistir chame o suporte.");
                return RedirectToAction(nameof(Excluir), new { id = id, saveChangesError = true });
            }

            return RedirectToAction(nameof(Index));
        }

        private bool CursoExiste(int id)
        {
            return _unitOfWork.Cursos.Listar(x => x.CursoID == id).Result.Count() > 0;
        }

        private List<SelectListItem> MontarSelectListDepartamentos(Curso curso = null)
        {
            var lSelectListDepartamentos = new List<SelectListItem>();
            var lDepartamentos = _unitOfWork.Departamentos.Listar().Result;

            lSelectListDepartamentos = lDepartamentos.Select(x =>
                new SelectListItem()
                {
                    Text = x.Nome,
                    Value = x.DepartamentoID.ToString(),
                    Selected = (curso != null && curso.DepartamentoID == x.DepartamentoID)
                }
            ).ToList();

            return lSelectListDepartamentos;
        }
    }
}

Universidade/Macoratti University - EF Core/Controllers/MatriculasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Universidade.Core.Entidades;
using Universidade.Infrastructure;
using Universidade.Infrastructure.Data;
using Universidade.Models;
using Universidade.Utility;

namespace Universidade.Controllers
{
    public class MatriculasController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IUnitOfWork _unitOfWork;
        public MatriculasController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var lCursos = await _unitOfWork.Cursos.ListarCursosDepartamentoEMatriculas();
                return View(lCursos.Select(x => _mapper.Map<CursoViewModel>(x)));
            }
            catch (Exception e)
            {
                this.AdicionarMensagemDeErro("Erro ao buscas matrículas. Tente novamente");
                return View(new List<CursoViewModel>());
            }
        }

        public async Task<IActionResult> Detalhes(int? id)
        {
            try
            {
                if (id == null)
                    return NotFound();

                var lCurso = await _unitOfWork.Cursos.BuscarCursoDepartamentoEMatriculasPorCursoId(id.Value);

                if (lCurso == null)
                    return NotFound();

                var lGerenciarMatriculasViewModel = new GerenciarMatriculasViewModel()
                {
                    Curso = _mapper.Map<CursoViewModel>(lCurso),
                    Matriculas = lCurso.Matriculas.Select(x => _mapper.Map<MatriculaViewModel>(x)).ToList()
                };

                return View(nameof(Detalhes), lGerenciarMatriculasViewModel);
            }
            catch (Exception e)
            {
                this.AdicionarMensagemDeErro("Erro ao carregar matriculas do curso. Tente novamente");
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpGet]
        public async Task<IActionResult> GerenciarMatriculas(int? id)
        {
            try
            {
                if (id == null)
                    return NotFound();

                var lCurso = await _unitOfWork.Cursos.BuscarCursoDepartamentoEMatriculasPorCursoId(id.Value);

                if (lCurso == null)
                    return NotFound();

                ViewBag.SelectListEstudantes = MontarSelectListEstudantes(lCurso);
                ViewBag.IdsEstudantesMatriculados = String.Join(";", lCurso.Matriculas.Select(x => x.EstudanteID));
                var lGerenciarMatriculasViewModel = new GerenciarMatriculasViewModel()
                {
                    Curso = _mapper.Map<CursoViewModel>(lCurso),
                    Matriculas = lCurso.Matriculas.Select(x => _mapper.Map<MatriculaViewModel>(x)).ToList()
                };

                return View(nameof(GerenciarMatriculas), lGerenciarMatriculasViewModel);
            }
            catch(Exception e)
            {
                this.AdicionarMensagemDeErro("Erro ao carregar matriculas do curso. Tente novamente");
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpPost]
        public async Task<IActionResult> GerenciarMatriculas(GerenciarMatriculasViewModel model, string idsEstudantesMatriculados)
        {
            try
            {
                if (model.Curso == null || model.Curso.CursoID < 1)
                {
                    this.AdicionarMensagemDeErro("Erro. Curso não informado");
                    return RedirectToAction(nameof(Index));
                }

                idsEstudantesMatriculados = idsEstudantesMatriculados ?? "";
                ViewBag.IdsEstudantesMatriculados = idsEstudantesMatriculados;
                var idsEstudantesMatriculadosArray = idsEstudantesMatriculados.Split(";", StringSplitOptions.RemoveEmptyEntries).Select(x=> Convert.ToInt32(x));

                var lCurso = await _unitOfWork.Cursos.BuscarCursoDepartamentoEMatriculasPorCursoId(model.Curso.CursoID);
                if (lCurso == null)
                {
                    this.AdicionarMensagemDeErro("Erro. Curso não encontrado");
                    return RedirectToAction(nameof(Index));
                }

                if (lCurso.Matriculas != null)
                {
                    foreach (var matricula in lCurso.Matriculas.Where(x => !idsEstudantesMatriculadosArray.Contains(x.EstudanteID)))
                    {
                        _unitOfWork.Matriculas.Deletar(matricula.MatriculaID);
                    }
                }

                foreach (var lIdEstudante in idsEstudantesMatriculadosArray)
                {
                    var lMatricula = new MatriculaViewModel()
                    {
                        Curso = null,
                        CursoID = lCurso.CursoID,
                        Estudante = null,
                        EstudanteID = lIdEstudante,
                        Nota = null
                    };

                    if (!lCurso.Matriculas.Any(x => x.EstudanteID == lIdEstudante))
                    {
                        _unitOfWork.Matriculas.Adicionar(_mapper.Map<Matricula>(lMatricula));
                    }
                }

                _unitOfWork.Complete();
                this.AdicionarMensagemDeSucesso("Matrículas modificadas com sucesso!");
            }
            catch(Exception e)
            {
                this.AdicionarMensagemDeErro("Não foi possível salvar. Tente novamente, e se o problema persistir chame o suporte.");
            }

            return RedirectToAction(nameof(Index));
        }

        public List<SelectListItem> MontarSelectListEstudantes(Curso curso)
        {
            var lSelectListEstudantes = new List<SelectListItem>();

            try
            {
                var lEstudantes = _unitOfWork.Estudantes.Listar().Result;
                lSelectListEstudantes.AddRange(lEstudantes.Select(x => 
                    new SelectListItem()
                    {
                        Text = $"{x.Nome} {x.SobreNome}",
                        Value = x.EstudanteID.ToString(),
                        Selected = curso.Matriculas != null && curso.Matriculas.Any(y => y.Estudante.EstudanteID == x.EstudanteID)
                    })
                );
            }
            catch(Exception e)
            {
                this.AdicionarMensagemDeErro("Erro ao buscar estudantes. Tente novamente");
                throw;
            }

            return lSelectListEstudantes;
        }

        private bool MatriculaExiste(int id)
        {
            return (_unitOfWork.Matriculas.Listar(x => x.MatriculaID == id).Result.Count() > 0);
        }
    }
}

Universidade/Macoratti University - EF Core/Views/Cursos/Detalhes.cshtml
@model Universidade.Models.CursoViewModel

@{
    ViewData["Title"] = "Details";
}

<div>
    <h4>Curso</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Creditos)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Creditos)
        </dd>
    </dl>
    <p></p>
</div>
<div>
    <a asp-action="Editar" asp-route-id="@Model.CursoID">Editar</a> |
    <a asp-action="Index">Voltar</a>
</div>

Universidade/Macoratti University - EF Core/Views/Cursos/Editar.cshtml
@model Universidade.Models.CursoViewModel

@{
    ViewData["Title"] = "Edit";
    var listaDepartamentos = (List<SelectListItem>)ViewBag.SelectListDepartamentos;
}

<h4>Curso</h4>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="ConfirmarEdicao">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CursoID" />
            <div class="form-group">
                <label asp-for="DepartamentoID">Departamento</label>
                @Html.DropDownList("DepartamentoID", listaDepartamentos, null, new { @class = "form-control", name = "DepartamentoID" })
            </div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Creditos" class="control-label"></label>
                <input asp-for="Creditos" class="form-control" />
                <span asp-validation-for="Creditos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LotacaoAlunos" class="control-label"></label>
                <input asp-for="LotacaoAlunos" class="form-control" />
                <span asp-validation-for="LotacaoAlunos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>    
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Universidade/Macoratti University - EF Core/Views/Cursos/Excluir.cshtml
@model Universidade.Models.CursoViewModel

@{
    ViewData["Title"] = "Delete";
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Curso</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Creditos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Creditos)
        </dd>
    </dl>
    
    <form asp-action="Excluir">
        <input type="hidden" asp-for="CursoID" />
        <input type="submit" value="Excluir" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar</a>
    </form>
</div>

Universidade/Macoratti University - EF Core/Views/Cursos/Index.cshtml
@model IEnumerable<Universidade.Models.CursoViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Inserir">Cadastrar Curso</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayName("Departamento")
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Creditos)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.QuantidadeMatriculas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LotacaoAlunos)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Departamento.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Creditos)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QuantidadeMatriculas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LotacaoAlunos)
            </td>
            <td>
                <a asp-action="Editar" asp-route-id="@item.CursoID">Editar</a> |
                <a href="@Url.Action("Detalhes", "Matriculas", new { id = item.CursoID})">Detalhes</a> |
                <a asp-action="Excluir" asp-route-id="@item.CursoID">Excluir</a>
            </td>
        </tr>
}
    </tbody>
</table>

Universidade/Macoratti University - EF Core/Views/Cursos/Inserir.cshtml
@model Universidade.Models.CursoViewModel

@{
    var selectListDepartamentos = (List<SelectListItem>)ViewBag.SelectListDepartamentos;
}

<h4>Curso</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Inserir">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DepartamentoID">Departamento</label>
                @Html.DropDownList("DepartamentoID", selectListDepartamentos, null, new { @class = "form-control", name = "DepartamentoID" })
            </div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Creditos" class="control-label"></label>
                <input asp-for="Creditos" class="form-control" />
                <span asp-validation-for="Creditos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LotacaoAlunos" class="control-label"></label>
                <input asp-for="LotacaoAlunos" class="form-control" />
                <span asp-validation-for="LotacaoAlunos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}